### ISSUE TITLE
Allow for complete name to be the name of the file instead of the path.

### ISSUE THREAD

**Issue by dragons4life** [MediaArea/MediaInfo#200]
This would be better as a default, but an option would be nice too.

**Comment by JeromeMartinez** [comment]
the complete name is intended for being able to retrieve the file, so has the maximum of information.
In advanced mode, there is the file name without extension on another line, not good?
Actually, what is the purpose of file name only?

BTW, better customization of the output will be one of the items for [voting](https://fr.mco.mediaarea.net/new/SupportUs/FAQ#votes) of [members](https://fr.mco.mediaarea.net/new/SupportUs/Individual).

**Comment by ahmedtds** [comment]
Isn't this same request as this I opened some time ago? : https://github.com/MediaArea/MediaInfo/issues/131

> Actually, what is the purpose of file name only?
Privacy. File paths may contain some personal informations. Excluding file paths and leaving only filenames prevents to share that info in a public forum or something accidently.

It should be a very simple feature to add. Would appreciate a lot if you consider it. Thanks!

**Comment by JeromeMartinez** [comment]
> Isn't this same request as this one I opened some time ago? : #131

Right, I definitely need to sort that at some point.

> Privacy. File paths may contain some personal informations. 

And lot of other fields may contain personal information.
There was [another discussion about that](https://sourceforge.net/p/mediainfo/feature-requests/528/), I copy paste:

<p>I have doubts about the security issue due to the complete file name, at least compared to all available information from a MediaInfo report, when lot of other sensitive pieces of information may be copied/pasted if one does not check what is copied, e.g. metadata sometimes contain the version of the tool used,  more problematic about security than a path in my opinion but you don't care about this part because it is less obvious.</p>
<p>Anyway, let's focus on "personally identifiable information". Difficulty here is that lot of users <strong>want</strong>  to have the complete name, for various reasons (e.g. used for locating the file in their big repository, and several files have the same base name), so changing the default output is not so easy to do.<br/>
Additionally, technically it is very difficult to know what is "personally identifiable information" e.g. a piece of metadata flagged as "free text" could contain your email adress ("personally identifiable information"), but also a contact email adress (not "personally identifiable information", actually the opposite, it is wanted to be public).</p>
<p>In my opinion the tool is neutral here, and the user needs to be careful about what he copy when doing copy/paste, about all lines from MediaInfo.<br/>
We are actually also thinking to such issue for another project (expanding <a class="" href="https://mediaarea.net/MediaInfoOnline" rel="nofollow">MediaInfoOnline</a>). This one already avoids to provide the complete name, but usage is different (no local installation, no parsing of a complete disk...).</p>
<p>We'll provide soon a method for sharing a MediaInfo report, in my opinion personally identifiable information removal should be handled only in this project because in that case there is no use case with a need of the complete file name. Note that in that case we plan to completely remove the file name line (so also the base name).</p>
<p>There is also a plan for <a class="" href="https://mediaarea.net/Vote/Mediainfo-Gui-Selection-Of-Which-Field-To-Display-27" rel="nofollow">having the user able to select which field to display</a>, it could be a method for removing such line so you don't forget, but a use "configuration" would be needed.</p>
<p>to be debated, but I don't see how I could do here for having everyone happy (both people not willing to configure for hidding the file name and people not willing to configure for showing the file name) and the choice of the default configuration looks like not so obvious.</p>
<hr/>

> It should be a very simple feature to add.

Difficulty is maintenance, and 1000x small becomes big for us.

**Comment by JeromeMartinez** [comment]
You can vote for this feature: 
[Vote for MediaInfo option to exclude file path](https://mediaarea.net/Vote/Mediainfo-Option-To-Exclude-File-Path-151).

**Comment by JeromeMartinez** [comment]
[Duplicate](https://github.com/MediaArea/MediaInfo/issues/131)
