### ISSUE TITLE
Add persistent numeric stream or track identifier

### ISSUE THREAD

**Issue by ptr727** [MediaArea/MediaInfo#201]
Please add a persistent numeric stream or track identifier.

I am trying to map the tracks from MediaInfo with MKVMerge --Identify and FFProbe.
MI produces details I use for logical processing, while I need to use MKVMerge and FFMpeg to modify the files and streams, but I somehow need to map the tracks identified in MI, with the same track in MKVMerge and FFMpeg.

MI produces ID, XSD says it is text, my samples are numeric and text, e.g. 3-CC1.
MI produces StreamOrder, XSD says it is text, my samples are all numeric, I assume non numeric is possible.
StreamOrder is missing for subtitle tracks.

Thank you

**Comment by JeromeMartinez** [comment]
> MI produces ID, XSD says it is text, my samples are numeric and text, e.g. 3-CC1.

Text includes digits, so not incompatible.
For MKVMerge, if I remind well it displays TrackID from MKV.
For Matroska files, MediaInfo displays TrackID and optionally (if there are more than 1 service in a track e.g. captions) a dash and other unique identifier for the service in the track (MKVMerge misses that because it does not detect services in the track).
So the link between MediaInfo and MKVMerge is to use MediaInfo ID field and take everything before the dash, then map it to MKVMerge output (remind that you can have several parts in MediaInfo for the same Track ID as MediaInfo displays services and MKVMerge tracks, so not 1 to 1 mapping by definition).
Note that if one day Matroska transport e.g. a Dolby E across 2 Matroska tracks, the ID will be "TrackID of first half-stream as seen by MKVMerge" + " / " + "TrackID of second half-stream as seen by MKVMerge", arbitrary decision in MediaInfo but I need to display IDs when there are more than 1 ID for a service (it happens...)

> StreamOrder is missing for subtitle tracks.

StreamOrder is usually (not 100% cases, corner cases to be studied) what could be mapped to Stream numbers in FFmpeg, **but** the definition of this field is not "I do like FFmpeg", because I have no idea of the algorithm behind FFmpeg. For Matroska, StreamOrder is the order of presence of the track in the track list.
If I understand well, you get a 608 caption in a MPEG Video in Track having ID 3 ("3-CC1"), so you can compute the ID of the track (here: "3") and find the corresponding MediaInfo part (here, I guess Video track), and get the StreamOrder of the subtitle track.
It is missing for the subtitle track, right, but I am not sure it would be useful for your goal.
Would it be useful for your goal that I fill the StreamOrder of subtitle track with the same number as in the video track?

If the answer is no, please provide more details about what you need (understanding that "mapping to FFmpeg" is not a need definition for MediaInfo, you need to specify the need from the Matroska spec and how a subtitle is interleaved in a video stream in mind, because I have no idea about what FFmpeg does and MediaInfo focuses on extracting information from a file, that's all).

An alternative could be to ask to FFmpeg that they provide at least the track ID in their output (I don't see it in the FFmpeg output, not easy for mapping)

Note: I don't have video stream with embedded "CC1" in a Matroska container, it would be good to provide one so I could see what FFmpeg does with it, and actually also what MediaInfo does with it.

> MI produces StreamOrder, XSD says it is text,

It is an integer, as it is an order. I'll change that.

**Comment by JeromeMartinez** [comment]
Just to be clear:

> Please add a persistent numeric stream or track identifier.

It is already there: first part (before the dash) of the `ID` field.
For Matroska, the first part (before the dash) of the `ID` field is mapped to `TrackNumber` Matroska field, and the first part (before the dash) of the `UniqueID` field is mapped to `TrackUID` Matroska field,
All after the dash is for doing a difference between different services inside the same Matroska track.
and all is "persistent".
I don't see the lack here, please suggest an output having in mind how a subtitle is interleaved in a video stream (so they get the same "persistent numeric stream or track identifier" if I don't add "-CC1") if the current output has an issue from your point of view.

**Comment by ptr727** [comment]
Thank you for the explanation.

I'm looking for something much simpler, just a numeric value, that will always be a number, for every track or stream, that will be the same number when running multiple times on the same file.

The order should ideally be the order for streams as found in the file, allowing a close mapping to MKVMerge and ffmpeg. MKVMerge makes life more difficult by having id and number and per the docs they are not necessarily sequential and not necessarily 1-based and 0-based, so that makes accurate mapping really hard. For now I map by the order of the track types, similar to ffmpeg.
E.g. order of audio, video, and subtitle tracks, mapping the respective id's across MediaInfo, MKVMerge, and FFMpeg.

Based on your description, ID is a good value, and the parsing is <unique track id>-<some other value>, so I will use ID and parse out text after -.

**Comment by ptr727** [comment]
I noticed the Id format changed, I now get Id's like thise: `<ID>1 / 8876149d-48f0-4148-8225-dc0b53a50b90</ID>`.
Should I change my parsing code to ignore anything after the space now?
