### ISSUE TITLE
Request: Could the Windows DLL versions without installer be delivered in ZIP format?

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfo#261]
@JeromeMartinez Could the DLL versions without installer be delivered in ZIP format?

The reason of a such request is that Maven plugins, not sure about Graddle plugin, support natively TAR, ZIP, GZ but 7Z is not.
So it should be more simple for the projects to get an updated version directly from your site as soon as it is available also if the project got not maintained anymore..

Regards

**Comment by JeromeMartinez** [comment]
Idea behind 7z usage is to lower disk and network usage, having 7z+ZIP increases disk usage, having only IP increases network usage.

How "get updated"? do you mean Maven scripts can download, unpack and put the DLL at the right place?

**Comment by Sami32** [comment]
Yes.
I didn't intended to support the 2 format for the DLL versions without installer, only ZIP but it add 2MB for the 2 files.
So it depend on the download frequency of these files and i will forget about it if that make your bandwidth usage grow up.
I was just hoping that these DLL versions was not downloaded a lot but my assumption could be totally wrong.

**Comment by Sami32** [comment]
No worry if it is an issue for you, as we could always continue to kept the version used in a repository like Sourceforge or Bintray without problem. I was just wondering.

Call it a "questionnable request" 😉

**Comment by JeromeMartinez** [comment]
Reopened because the request makes sense, was just asking for more details about how it would be used.

**Comment by Nadahar** [comment]
The idea was that our build system would download, unpack and deploy the library in the correct location in our "binary bundle".

I objected however, because I don't want the builds to link to things that we don't know will stay there "forever". I've been bitten by this too many times: if you need to build an old version for some reason and check out an old commit/tag, the build fails because some of the URL's aren't valid anymore. That can be a real hassle to get around, and chances are that the person trying to build doesn't even know enough the build system to fix it.

According to @Sami32 you delete old versions when you need the disk space, which is perfectly understandable, but it would mean that older builds would fail. Therefore I think it's better that we host the binaries somewhere were links are "guaranteed" to remain valid. 

The ideal solution would probably have been to store them somewhere like the [archive.org Open Source Software Collection](https://archive.org/details/open_source_software).

**Comment by Sami32** [comment]
@nadahar Sorry, it seem that i was wrong. I just discovered that link:
https://mediaarea.net/download/binary/libmediainfo0/

Until now did only knew the SNAPSHOT one and the VideoHelp one that keep trace of the GUI versions only with rare exceptions.
So i discovered at the same time that the DLL JavaScript versions was alreadly using the ZIP format.

**Comment by JeromeMartinez** [comment]
[Enable ZIP creation in source code](https://github.com/MediaArea/MediaInfoLib/pull/900/files), [release engine](https://github.com/MediaArea/MediaArea-Utils/pull/192/files), [download page update](https://github.com/MediaArea/MediaArea-Website/pull/201/files) (for next release).

**Comment by Sami32** [comment]
Thank you very much :smiley:
Have a nice day.

**Comment by Sami32** [comment]
As a side note, the **License.html** file found [here](https://mediaarea.net/download/binary/mediainfo/18.05/MediaInfo_CLI_18.05_Windows_i386.zip) and [there](https://mediaarea.net/download/binary/mediainfo/18.05/MediaInfo_CLI_18.05_Windows_x64.zip) are 4 years old outdated.
There are fine in https://mediaarea.net/download/binary/libmediainfo0/.

**Comment by JeromeMartinez** [comment]
> I objected however, because I don't want the builds to link to things that we don't know will stay there "forever".

We try to keep it "forever", we would break this rule only if we have a very good reason to do so.

> According to @Sami32 you delete old versions when you need the disk space,

We move them from our CDN, but links stay same, so no issue on your side (a bit slower than before but I think you would not care about losing few hundreds of milliseconds in that case).

**Comment by Nadahar** [comment]
@JeromeMartinez Thanks for the info. That changes things. The download speed for old builds are of importance, I don't expect it to be a frequent even.

**Comment by JeromeMartinez** [comment]
> As a side note, the License.html file found here and there is 4 years old outdated.

[Fixed](https://github.com/MediaArea/MediaInfo/pull/262), thanks for report.
