### ISSUE TITLE
Dolby Digital Plus Detection

### ISSUE THREAD

**Issue by DubDuck** [MediaArea/MediaInfo#269]
Hi.
MediaInfo now detects E-AC-3 into a wrong bitrate. I assume it's not fully supported. Any idea of fixing?

Audio
ID : 2
Format : E-AC-3
Format/Info : Enhanced Audio Coding 3
Codec ID : A_EAC3
Duration : 2 min 42 s
Bit rate mode : Constant
Bit rate : 500 b/s
Channel(s) : 8 channels
Channel(s)_Original : 6 channels
Channel positions : Front: L C R, Side: L R, LFE
Sampling rate : 48.0 kHz
Frame rate : 187.500 FPS (256 SPF)
Compression mode : Lossy
Stream size : 24.7 MiB (64%)
Service kind : Complete Main
Default : Yes
Forced : No

sample https://nofile.io/f/Twb7S2WWtCc#d5fe63d16a8f592e

**Comment by JeromeMartinez** [comment]
Due to non "pure" E-AC-3 stream (the core stream is in AC-3), and MediaInfo was not well supported such hybrid content (AC-3 for core and E-AC-3 for additional channels)

Fixed in https://github.com/MediaArea/MediaInfoLib/pull/896, you can test a [development snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/).
