### ISSUE TITLE
Feature request: Will my device play it?

### ISSUE THREAD

**Issue by kevingy** [MediaArea/MediaInfo#355]
I love MediaInfo. It provides a huge amount of very technical information. Perhaps it provides too much information. At the end of the day, all I personally care about is "Will my Roku play the selected file - yes or no?" Most of the time, I don't care if the file plays on my computer.

The supported video and audio formats for a variety of devices (including Roku) are well known. I request adding a feature to MediaInfo that indicates the supported devices upon which the selected will play. If you wanted support an advanced feature, the MediaInfo user would configure the devices he or she cares about. When MediaInfo scans the file, an immediate visual indication could appear if the file will play on all, some, or none of the devices the user has configured.

**Comment by JeromeMartinez** [comment]
This is something we have in mind for years, but we don't find any financial sustainability for that, as it is a big thing to do (we need to have a list of compatible format/features per machine: starting the project then maintain it), and nobody is interested in sponsoring us for that for the moment, at least as far as we know.

If you think you can motivate people to crowdfund such project, I could [add it to the list of votes](https://mediaarea.net/Vote) and see how much interest there is really.

**Comment by kevingy** [comment]
It seems like the hard work is done. The application has already determined the media properties. From there, it's matter of mapping the file properties to the known device properties. Typically, the device properties don't change. Only new devices are released at a rate of one or two per year across all manufacturers.

It seems odd to me that an open source project only does things that are financially motivated. If that's your process, I guess it is what it is. I'll add it to the list and see what happens.

**Comment by JeromeMartinez** [comment]
> The application has already determined the media properties. 

Not all the ones which may prevent a playback.
You could have 2 files with same MediaInfo report but 1 is not playing on a player, and it would request immediate analysis in order to have users confident in the result of the report you want.

>  From there, it's matter of mapping the file properties to the known device properties

If it is so easy, feel free to send a patch demonstrating how easy it is (it i open source, anyone can demonstrate that!)

> It seems odd to me that an open source project only does things that are financially motivated. 

Why?
Please show me where in open source definition there is any limitation about that.
Note that we often implement stuff without financial sponsorship, but usually this is small or with a long term business in mind in order to have some sustainability of the project, here it is not the case, and we never say that a "project only does things that are financially motivated", just that I, the main developer, don't think that I'll do it for free especially due to the cost (in time or $, as you prefer) of such request. Anyone one earth may disagree and prove it by implementing the feature for free.

You previously said:

> It provides a huge amount of very technical information.

A reason for that is that we work on it as our main job, and as far as I know my employees prefer financial motivation over just "hey, this is MediaInfo", and my food store does not want to be paid with "hey, I am the MediaInfo developer" words, they requests money. If you find people ready to work for us for free, I am interested (you? ;-) ).

Note that you seem to think that there is no need of financial motivation, and it is open source, so everyone on earth is responsible if it does not happen, not just us. Feel free to ask to anyone on earth why they are not interested in developing this feature.

> I'll add it to the list and see what happens.

Actually we are the only ones who can add a new vote item, I just prefer to wait for a first MediaArea real financial supporter saying this is a feature he would like before creating the corresponding item, so just drop us a mail or here with your MediaArea login associated to a supporter package, and we'll add the item. I am lazy to create vote items without a single vote, and too many people say that they will vote and don't do it in reality.
And if you just wait, there is little chance that something happens, you need to find and motivate other potential supporters (or developers) of this feature.

**Comment by kevingy** [comment]
OK, nevermind then.
