### ISSUE TITLE
How to compile with Libcurl support?

### ISSUE THREAD

**Issue by bushev** [MediaArea/MediaInfo#357]
Hi, it looks like `--with-libcurl` is not currently supported.

I'm getting a warning message when I'm trying to specify it:

```
configure: WARNING: unrecognized options: --with-libcurl
```

**Comment by JeromeMartinez** [comment]
`--with-libcurl` is fine, warning may be there because in some "all in one" scripts we provide this flag to all packages, but the only one needing this option is libmediainfo.

**Comment by JeromeMartinez** [comment]
> I'm expecting that all required libraries will be statically linked, but they don't. What I missed?

Idea behind ` --enable-static` is to build all required **non system** libs (the ones in the packages you downloaded) as static, and libcurl is a system lib (not in the package) in theory easily available on your target machine, so not needed in static builds by everyone.
You may try to add ` --enable-staticlibs` for what you are looking for.

**Comment by bushev** [comment]
I got it, thanks! I'll copy `libcurl` from the build machine.

**Comment by ninjada** [comment]
have a node8 lambda function working correctly. trying to migrate to node10 and running the mediainfo build process under an amazonlinux2 docker image and hitting the same issues in this issue. if i run with --enable-static, i get the error above with libcurl.so.4 cannot open shared object.

> > I'm expecting that all required libraries will be statically linked, but they don't. What I missed?
> 
> Idea behind ` --enable-static` is to build all required **non system** libs (the ones in the packages you downloaded) as static, and libcurl is a system lib (not in the package) in theory easily available on your target machine, so not needed in static builds by everyone.
> You may try to add ` --enable-staticlibs` for what you are looking for.

Hi @JeromeMartinez 

As above running into this issue, but --enable-staticlibs is giving me further error on build:

Reader_libcurl.cpp:(.text+0x97e1): undefined reference to `curl_easy_getinfo'
collect2: error: ld returned 1 exit status
make: *** [mediainfo] Error 1
Problem while compiling MediaInfo (CLI)

How can I include this?

@bushev how did you resolve exactly?

**Comment by bastianbb** [comment]
> I got it, thanks! I'll copy `libcurl` from the build machine.

@bushev how can we do this?

**Comment by bushev** [comment]
Hey guys,

there is how I did that (for AWS Lambda):

![image](https://user-images.githubusercontent.com/7535766/72544543-97e58b00-3855-11ea-8f5b-591e04d7c326.png)

**Comment by bastianbb** [comment]
Thank you, and what options have you used to compile the binary?

**Comment by bastianbb** [comment]
@bushev Thanks, what do you mean with shared library? I followed all the steps but it continues to give me:

**error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory"**

when executing the lambda.
I used the same directory structure as you, and i have taken libcurl.so.4 and libcurl.so.4.5.0 from /usr/lib64 inside the Docker.

**Comment by bushev** [comment]
@bastianbb 

Yeah, just one more thing - environment variable `LD_LIBRARY_PATH` tells were to search for the libraries.

![image](https://user-images.githubusercontent.com/7535766/72556908-a63fa100-386d-11ea-95d0-64a444790087.png)

**Comment by bastianbb** [comment]
@bushev done but nothing, same error:
<img width="546" alt="Schermata 2020-01-16 alle 21 05 26" src="https://user-images.githubusercontent.com/23718032/72558947-005b5900-38a4-11ea-8678-db44f49dd5ab.png">

**Comment by g-maxime** [comment]
Here a Dockerfile for building mediainfo CLI with static libcurl and OpenSSL:
https://gist.github.com/g-maxime/aedcb7d5d765b262abdff889f3d3bd30

This simplify a lot deploying on AWS Lambda.

**Comment by bastianbb** [comment]
I'm sorry. I forgot to answer, thanks @g-maxime your Dockerfile helped me to solve the issue.
I wasn't able to compile with: --with-libcurl and --enable-staticlibs together, and installing zlib-devel instead of libcurl-devel on the image allowed me to compile correctly without the error encountered by @ninjada.
Now my Lambda is finally working again with nodejs 12!!!

**Comment by basimhennawi** [comment]
Hi guys, I had the same problem upgrading AWS Lambda runtime from nodejs 8 to 10/12 that my old `mediainfo` static file fails, so I build @g-maxime 's docker file and get the new `mediainfo` file along with `libcurl.so.4` and `libcurl.so.4.5.0` files but still got this: `error while loading shared libraries: libnghttp2.so.14: cannot open shared object file: No such file or directory` , can somebody just for sake of testing upload his current static working files with the newer nodejs version? Thanks in advance!

**Comment by JeromeMartinez** [comment]
> can somebody just for sake of testing upload his current static working files with the newer nodejs version?

Check files with "Lambda" in their name in our [development snapshots](https://mediaarea.net/download/snapshots/binary/mediainfo/).

**Comment by basimhennawi** [comment]
It works! Thanks @JeromeMartinez ❤️

**Comment by marklassau** [comment]
Thanks to @g-maxime's Dockerfile I managed to build a lambda compatible version of `mediainfo` (awesome project BTW, guys!).
Quick note for the next person trying this:
It seems that now you need `perl-core` in order to build openssl so make sure you also `yum install perl-core` as described at https://github.com/openssl/openssl/blob/master/NOTES-Perl.md

**Comment by cloudtagger** [comment]
The lambda download of mediainfo in the download area did not work for me. The one from the latest development snapshot that @JeromeMartinez linked to did work. Maybe the website download area needs updating to the latest compiled lambda version.

**Comment by JeromeMartinez** [comment]
An official new release is planned next week, we'll update the website at this moment.

**Comment by cloudtagger** [comment]
One more thing. With  @g-maxime docker file it seems you still need to grab the .so libs for it to work. The only version I have found built or Docker that works with just the mediainfo file alone and no other files is the latest dev snapshot for lambda.

**Comment by g-maxime** [comment]
@cloudtagger What is the error?

If I run ldd against the mediainfo binary from the docker image, I get only basic system dependencies:
```
	linux-vdso.so.1 (0x00007ffc90b55000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f8933b0a000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f8933b03000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8933ae1000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f89338f1000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f89337ab000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8933790000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f89335c4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8933b4d000) 
```

**Comment by JeromeMartinez** [comment]
Just to be clear about the .so "issue", we talk about the corresponding [libmediainfo development snapshots](https://mediaarea.net/download/snapshots/binary/libmediainfo0/), right?

**Comment by cloudtagger** [comment]
In lambda I get that mediainfo can't find libcurl. don't know why. maybe I need to try again and see.

**Comment by aniket-amagi** [comment]
@cloudtagger I am facing similar issue , I also have raised an issue (https://github.com/iandow/mediainfo_aws_lambda/issues/4). Please let me know if you make some progress.

**Comment by marklassau** [comment]
A bit of information to try and clear up some of the confusion: it makes a huge difference which "lambda runtime" you are running in.
Have a look at https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

What I found is that running in the `Python 2.7` runtime everything is rosy - all the libs are already available.
However in `Node.js 12` there are lots of libs missing.

I note that the former claims to use `Amazon Linux` while the latter claims `Amazon Linux 2`.
However, that does not seem to be all there is to it - because if you start an EC2 instance with `Amazon Linux 2` then you _do_ get those libs.

It seems that at least some of the Lamdba runtimes are totally stripped down.
So - be aware that a mediainfo build that works in one Lambda runtime does not necessarily work in all runtimes :(


I noted above that  @g-maxime's Dockerfile worked for me (after some updates) and that was in `Node.js 12` runtime.
The one issue with his procedure is that it builds from latest source of underlying libs - so it will bitrot.

**Comment by tdfacer** [comment]
I was running into this issue and preferred not to use a layer, so I downloaded the [layer](https://mediaarea.net/en/MediaInfo/Download/Lambda) locally, unzipped it, and included the binary w/ my lambda source code bundle.

This seems to be working for me so far, although I _may_ end up using a layer eventually.

**Comment by JeromeMartinez** [comment]
> So - be aware that a mediainfo build that works in one Lambda runtime does not necessarily work in all runtimes :(

We are not aware of any "non compatible" Amazon Linux version, now we support both `Amazon Linux` (the previous versions were working only on this one because `libcurl` is missing in the new one, and the current versions work on it as we "just" included `libcurl` in our binary without breaking something else) and `Amazon Linux 2`.
