### ISSUE TITLE
Hi, the gpg key for the Ubuntu repos...

### ISSUE THREAD

**Issue by alicektx** [MediaArea/MediaInfo#408]
...seems to have expired as of today?
(The following signatures were invalid: KEYEXPIRED 1579793674 etc etc)...

All the best

**Comment by mirolm** [comment]
Same with the debian repository key:

````
Err:13 https://mediaarea.net/repo/deb/debian buster Release.gpg
  The following signatures were invalid: EXPKEYSIG C10E11090EC0E438 MediaArea <info@mediaarea.net>
````

**Comment by JeromeMartinez** [comment]
Thanks for your feedback. We are working on fixing that.

**Comment by JeromeMartinez** [comment]
For users of Debian based distributions (Debian, Ubuntu, Mint...), you need to download a new MediaArea repo package at https://mediaarea.net/en/Repos
It is due to the expiration of a GPG key on 2020-01-23 we inadvertently forgot, we updated the date but your system will refuse to take it in account for security reasons. The GPG key signature did not change.

**Comment by userdocs** [comment]
I did that but it was a partial fix. this was a is a working method for me.

~~~
wget https://mediaarea.net/repo/deb/repo-mediaarea_1.0-12_all.deb && dpkg -i repo-mediaarea_1.0-12_all.deb
apt-key adv --recv-keys --keyserver  https://mediaarea.net
apt update
~~~

**Comment by alicektx** [comment]
...All working fine here now (please feel free to close the issue whenever you feel it's ok to do so, ie. that people have been notified about such etc)...

Deeply thanks for all of your hard work on MediaInfo throughout all those years btw :+1:
