### ISSUE TITLE
Recipe.h License 

### ISSUE THREAD

**Issue by Silviu-Caprar** [MediaArea/MediaInfo#411]
Hi there,

Regarding the following file, https://github.com/MediaArea/MediaInfo/blob/v18.08.1/Project/AppImage/Recipe.sh 

Can you please specify if both GPL v3+ and MPL v2+ license apply or we can just choose one of the two ?

Thank you,

**Comment by JeromeMartinez** [comment]
This is an unfortunate typo, linked "[License.html](https://github.com/MediaArea/MediaInfo/blob/master/LICENSE) file in the root of the source tree" is BSD-2-Clause.
Fix on the way, license of this file is BSD-2-Clause.
(for the moment only the files in /debian are not with this license, because they were not created by us).

**Comment by JeromeMartinez** [comment]
We fixed the license in https://github.com/MediaArea/MediaInfo/pull/412.
As it was a typo, I indicate here that the license was always intended to be BSD (indicated in the linked `License.html`) and BSD license should be preferred also for older versions, and if not possible pick one of the previous indicated licenses.
