### ISSUE TITLE
Mediainfo reports wrong AAC profile.

### ISSUE THREAD

**Issue by sebma** [MediaArea/MediaInfo#44]
Hi,

Mediainfo (v0.7.85) reports wrong AAC profile on the video that can be found here : https://www.dailymotion.com/video/x2gi7nf

Once downloaded (146MiB), if I run `mediainfo` : 

```
$  mediainfo -f Le_meilleur_des_mondes_-_Technologie__http-380__x2gi7nf.mp4 | grep -v Cover_Data | egrep -wi "aac|he"
Audio_Format_List                        : AAC
Audio_Format_WithHint_List               : AAC
Audio codecs                             : AAC LC-SBR
Format                                   : AAC
Commercial name                          : AAC
Format profile                           : HE-AAC / LC
Codec                                    : AAC LC-SBR
Codec                                    : AAC LC-SBR
Codec/Family                             : AAC
```

But `mp4info` (from [mp4v2-utils](http://code.google.com/p/mp4v2/)) says this : 
```
$ mp4info Le_meilleur_des_mondes_-_Technologie__http-380__x2gi7nf.mp4 | grep audio
2	audio	MPEG-4 AAC LC, 2649.814 secs, 64 kbps, 44100 Hz
```

and my Blu ray player is able to play it but cannot any of my videos containing HE-AAC audio.

I concluded that what `mp4info` says is right: this video does not contain HE-AAC audio but standard AAC-LC.

Can you check and fix this ?

**Comment by JeromeMartinez** [comment]
> Once downloaded (146MiB),

I tested a file of 152 MB / 145 MiB (151 612 374 bytes), MD5 5d747aa49a37e81a2f750a5a0f61be41 (if it is the wrong one, please provide directly the file instead of a Daily motion web page)

the MP4 DecoderConfigDescrTag contains SBR extension:

    000AF380          DecoderConfigDescrTag (28 bytes)
    000AF380           Header (5 bytes)
    000AF380            type:                                   4 (0x04)
    000AF381            size:                                   128 (0x80)
    000AF382            size:                                   128 (0x80)
    000AF383            size:                                   128 (0x80)
    000AF384            size:                                   23 (0x17)
    000AF385           objectTypeIndication:                    64 (0x40)Audio ISO/IEC 14496-3 (AAC) - 
    000AF388           streamType:                              5 (0x05)(6 bits) - AudioStream - 
    000AF387           upStream:                                No
    000AF386           reserved:                                Yes
    000AF387           bufferSizeDB:                            87500 (0x0155CC)
    000AF38A           maxBitrate:                              440000 (0x0006B6C0)
    000AF38E           avgBitrate:                              63999 (0x0000F9FF)
    000AF392           DecSpecificInfoTag (10 bytes)
    000AF392            Header (5 bytes)
    000AF392             type:                                  5 (0x05)
    000AF393             size:                                  128 (0x80)
    000AF394             size:                                  128 (0x80)
    000AF395             size:                                  128 (0x80)
    000AF396             size:                                  5 (0x05)
    000AF397            AudioSpecificConfig (4 bytes)
    000AF397             audioObjectType - 2 - LC (0 bytes)
    000AF39A              audioObjectType:                         2 (0x02)(5 bits) - 
    000AF39E             samplingFrequencyIndex:                   7 (0x07)(4 bits) - 22050 - 
    000AF39A             channelConfiguration:                     2 (0x02)(4 bits) - Front: L R - 
    000AF39A             GASpecificConfig (18446744073709551615 bytes)
    000AF399              frameLengthFlag:                         No1024 bytes - 
    000AF398              dependsOnCoreCoder:                      No
    000AF397              extensionFlag:                           No
    000AF39C             syncExtensionType:                        695 (0x02B7)(11 bits) - 
    000AF39C             extensionAudioObjectType - 5 -  (18446744073709551615 bytes)
    000AF397              audioObjectType:                         5 (0x05)(5 bits) - 
    000AF39E             sbrPresentFlag:                           Yes
    000AF39A             extensionSamplingFrequencyIndex:          4 (0x04)(4 bits) - 44100 - 
    000AF397            Padding:                                   0 (0x0)

I also checked the 1st AAC frame, it contains SBR data:

    0011F08D    FIL - fill_element (30 bytes)
    0011F092     id_syn_ele:                              6 (0x06)(3 bits) - FIL - fill_element - 
    0011F08E     count:                                   12 (0x0C)(4 bits) - 
    0011F08E     extension_payload (29 bytes)
    0011F092      extension_type:                         13 (0x0D)(4 bits) - 
    0011F092      sbr_extension_data (25 bytes)
    0011F091       bs_header_flag:                        Yes
    0011F091       sbr_header (18 bytes)
    0011F090        bs_amp_res:                           1 (0x01)(1 bits) - 
    0011F08C        bs_start_freq:                        14 (0x0E)(4 bits) - 
    0011F090        bs_stop_freq:                         10 (0x0A)(4 bits) - 
    0011F08D        bs_xover_band:                        0 (0x00)(3 bits) - 
    0011F093        bs_reserved:                          0 (0x00)(2 bits) - 
    0011F092        bs_header_extra_1:                    Yes
    0011F091        bs_header_extra_2:                    No
    0011F08F        bs_freq_scale:                        2 (0x02)(2 bits) - 
    0011F08E        bs_alter_scale:                       1 (0x01)(1 bits) - 
    0011F08C        bs_noise_bands:                       3 (0x03)(2 bits) - 
    0011F08C       sbr_data (31 bytes)
    0011F08C        sbr_channel_pair_element (31 bytes)

Note: the presence of SBR data means that this is an HE-AAC content.

> and my Blu ray player is able to play it but cannot any of my videos containing HE-AAC audio.

Would be weird: HE-AAC is by design invisible to non HE-AAC aware decoders, so if your player is not able to play it, it just plays the legacy layer (so 22 kHz content)

VLC also says that it is HE-AAC.

**Comment by sebma** [comment]
Hi,

This command : `youtube-dl -f http-380 https://www.dailymotion.com/video/x2gi7nf` will download the 146MiB file.

You talk about 22kHz audio, but `mediainfo` says : 

`Sampling rate                            : 44.1 KHz / 22.05 KHz`

and VLC says the audio is 44.1kHz

So what is the real sample rate used in the audio ?

I'd like to encode videos with HE-AAC audio playable by my Blu-ray player.

I have re-encoded the audio of this file with `ffmpeg` using the following command : 

`ffmpeg -i Le_meilleur_des_mondes_-_Technologie__http-380__x2gi7nf.mp4 -vcodec copy -acodec libfdk_aac -aprofile aac_he -vbr 3 -movflags frag_keyframe Le_meilleur_des_mondes_-_Technologie__http-380__x2gi7nf_HE-AAC-VBR.mp4 -y`

But the resulting cannot be played.

**Comment by JeromeMartinez** [comment]
> This command : youtube-dl -f http-380 https://www.dailymotion.com/video/x2gi7nf will download the 146MiB file.

I don't have youtube-dl. So I hope that we speak of the same file.

> So what is the real sample rate used in the audio ?

44.1 kHz for HE-AAC capable players
22.05 kHz for **non** HE-AAC capable players (i.e. AAC LC players)
This is the reason both sample rates are displayed (both are valid, the selected sample rate depends of the capability of the player).

See [Spectral Band Replication](https://en.wikipedia.org/wiki/Spectral_band_replication) for more information about HE-AAC features and the reason legacy players can play HE-AAC (but only at 22.05 kHz)
or [HE-AAC](https://en.wikipedia.org/wiki/High-Efficiency_Advanced_Audio_Coding#Decoding) page:
"Older versions of Apple iTunes, iPod Touch, and iPhone will play HE-AAC files at reduced fidelity because they ignore the spectral-band replication and parametric stereo information, instead playing them as though they were standard AAC-LC files without the high-frequency, or "treble," information that is only present in the SBR part of the signal."

> and VLC says the audio is 44.1kHz

VLC supports HE-AAC so plays at 44.1 kHz, right.

> I'd like to encode videos with HE-AAC audio playable by my Blu-ray player.

I can not help about that, and it is not the purpose of MediaInfo. MediaInfo says the content of the file.
and "AAC-LC 44.1 kHz" is wrong here, it is "HE-AAC 44.1 kHz" or "AAC-LC 22.05 kHz" depending of the player capability.

**Comment by sebma** [comment]
We speak of the same file, the file size is 144.59MiB.

My file was 146 MiB, because both the jpg cover and metadata were included by my `youtube-dl` config.

I've been looking at my DVD player specs. but they're not precise enough regarding the AAC profiles.

I guess I'll have to open it to see the name of the chip and try and find it's specs on Google.

Thanks a lot for your HE-AAC explanation.
