### ISSUE TITLE
Detect "yuvj420p" using mediainfo reports?

### ISSUE THREAD

**Issue by pjotrek-b** [MediaArea/MediaInfo#484]
Hi!
This is a question, not an issue :grinning:

I have hundreds of files with (ffmpeg-speak) "pix_fmt yuv**j**420p" (=_planar YUV 4:2:0, 12bpp, full scale (JPEG)_), which is "[_deprecated in favor of AV_PIX_FMT_YUV420P and setting color_range_](https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/pixfmt.h#L78)".

MediaInfo correctly translates both,  "**yuvj420p**" and "**yuv420p + color_range=pc/jpeg**" to this (which makes them look identical to me):
- Color space : YUV
- Chroma subsampling : 4:2:0
- Bit depth : 8 bits
- Color range : Full

Is it possible to see the difference between these two variants in MediaInfo reports somehow?

Thank you very much in advance!

**Comment by JeromeMartinez** [comment]
This is very FFmpeg language, I need to know the file language, i.e. the difference inside the file (if there is one)
Please provide 2 sample files, whose you want to catch a difference in the configuration.
(here, I would bet on the Codec ID but not sure)

**Comment by pjotrek-b** [comment]
I'm also curious to find out what the _actual_ difference is!
Will provide 2 samples :smile:

Thanks again!

**Comment by pjotrek-b** [comment]
Hm. Nevermind:
When encoding H.264(yuvj420) _to_ h.264(yuv420p) it says:
Output is `yuv420p(pc, smpte170m/bt709/bt709)`

...but when reading that file again with ffprobe (current git version), it's interpreted as:
`yuv**j**420p(pc, smpte170m/bt709/bt709)`

This puzzles/surprises me, but I then this is not a Mediainfo, but ffmpeg question.
Sorry and thanks!

**Comment by JeromeMartinez** [comment]
> This puzzles/surprises me,

IIUC it is just internal code, and some parts of FFmpeg are updated to the new internal (not storage related, just in FFmpeg workflow) metadata then some others are not (yet).

**Comment by pjotrek-b** [comment]
Seems like.
I've posted the question on ffmpeg-user: "[Correct conversion of yuvj420p?](http://www.ffmpeg-archive.org/Correct-conversion-of-yuvj420p-tp4693897p4693946.html)"

And I'll close this issue here then.

**Comment by ValZapod** [comment]
> then some others are not

Some, like jpeg 2000 (libopenjpeg and native jpeg2000) outright do not support that deprecated pixel format at all and quit if you will ask for that.

Some like raw stuff has the same MKTAG('I', '4', '2', '0') for both yuvj and yuv see https://github.com/FFmpeg/FFmpeg/blob/f7fd205f11d5299d6a16b0ff0ae85fddb32772f2/libavcodec/raw.c#L44

YUVJ is only used in jpeg because it uses full range (a.k.a. pc range). Even here if you will looks into Windows XP source code of NIFTY framework there was a giant amount of problems to handle all of it (PhotoYCC and YUVK (not the same as CMYK) being some of those crazy pixel formats and two broken by Microsoft handlers).

It is just an abstraction over various different color range signaling in various file formats (AVCOL_RANGE_JPEG and AVCOL_RANGE_MPEG are key to that abstraction, that is full and narrow (a.k.a low, a.k.a. studio, a.k.a. tv) ranges respectively). Not EVERYTHING is even supported. For example from not so long support was added to DPX files and fixed in mxf encoder: https://github.com/FFmpeg/FFmpeg/commit/abd58a4192e4c5ea721b22365c211d8fa874f3d2 https://github.com/FFmpeg/FFmpeg/commit/8232e01e41488bc3f4504b3de241106a4cca7cb7

And it is of course even more complex than that, because it can be signaled in SEI, signaled in container, signaled of the original content range can be supported to, changed on the fly, etc, etc.

You can look up the insane world of that stuff using https://github.com/FFmpeg/FFmpeg/search?p=4&q=AVCOL_RANGE_MPEG&type=code
