### ISSUE TITLE
PID SCTE35 recognition

### ISSUE THREAD

**Issue by Anas92230** [MediaArea/MediaInfo#497]
Hi,

Mediainfo(v.20.09) doesn't recognize PID SCTE35 in my file. How it's possible? I don't do a right command(mediainfo --Output=JSON file.ts)?
OS : Ubuntu 20.04.

thanks for your help

**Comment by JeromeMartinez** [comment]
> Mediainfo(v.20.09) doesn't recognize PID SCTE35 in my file. 

As far as I know, MediaInfo has internally some code for parsing SCTE 35 due to some users expanding the code for doing some tests on SCTE 35 content, but no output of the SCTE 35 PID in the open source version.

> How it's possible?

Not implemented. Why do you expect it for sure?
It could be implemented as you would like it, but not currently our priority (not the priority of [our sponsors](https://mediaarea.net/Services)).

**Comment by Anas92230** [comment]
Thank you Jérôme.
I use mediainfo for detect all pid in my file. For me you probably use information in PMT or not? I don't want to extract information from pid  just identify it.

**Comment by JeromeMartinez** [comment]
I use the PMT but currently skip elements not recognized (so here SCTE 35 pid is skipped). Not the best behavior and it would be great to change that, but this is the current one.

**Comment by Anas92230** [comment]
Ok it's unfair for scte 😁
I use some tools to complet analyze on my files  and I hope that will be added in next version 👍.

Thank you Jérôme.
