### ISSUE TITLE
TIFF invalid floating point operation

### ISSUE THREAD

**Issue by levicki** [MediaArea/MediaInfo#508]
Attempting to open a DNG file in MediaInfo GUI 20.09 x64 on Windows 10 Version 10.0.19042.630 results in the following error:

![image](https://user-images.githubusercontent.com/16415478/100547366-a880d300-3266-11eb-9465-8760ee5756e4.png)

If I am not mistaken, it should at least say "format not supported", not error out like this?

Also, opening the same DNG file via MediaInfoOnline kind of works:

![image](https://user-images.githubusercontent.com/16415478/100547407-d6feae00-3266-11eb-8906-776ee8107a08.png)

But the image is misdetected as being TIFF (which I assure you it is not), the resolution is wrong (should be 4032 x 3024) and it lacks all other EXIF data so my guess is that it is probably detecting and decoding thumbnail only.

Is DNG supported at all and if not, why not?

**Comment by JeromeMartinez** [comment]
We currently don't support DNG.
DNG is more or less an extension to TIFF, so it is not surprising that it is detected as TIFF (complain the spec authors for having non DNG readers peeking the thumbnail data :) ).

Please provide the file, the DNG files we have don't have this crash and we want to avoid crashes as much as possible.

> it lacks all other EXIF data 

EXIF is currently not supported. It may be a big task due to lot of proprietary implementations... (not sure if we would like to implement our own lib or if we would tale an external lib, less costly but less control). But Maybe we'll integrate more or less soon a basic version.

> Is DNG supported at all and if not, why not?

No [sponsor](https://mediaarea.net/Services) for it.

**Comment by levicki** [comment]
Here is the file you requested:

[IMG_0793.zip](https://github.com/MediaArea/MediaInfo/files/5612695/IMG_0793.zip)

**Comment by JeromeMartinez** [comment]
Crash fixed (https://github.com/MediaArea/MediaInfoLib/pull/1335).
I renamed the issue ticket in order to focus on the crash, for DNG support please open a dedicated ticket.
For EXIF, there is a couple of libraries with a compatible license, I am not sure yet if I use one of them or a "not invented here" internal parser, the biggest difficulty is to handle proprietary items (and there are tons of them). But sure at some point I should implement at least a basic parser especially because more and more users are on Android and want to see the GPS/date of the pictures.

**Comment by levicki** [comment]
That was quick.

As for EXIF, bear in mind that people use this tool on PC and that showing more info for images would be great.

In addition to GPS data you mentioned, color temperature, ISO speed, exposure time, focal length, etc, as well as some JPEG specific details such as chroma subsampling, colorspace, baseline vs progressive, ICC profile (if embedded), and approximate quality it was saved with would be useful.
