### ISSUE TITLE
Mediainfo misreports QT caption track frame rate as 23976/1000 instead of 24000/1001

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfo#636]
Frame rate of text tracks for 24000/1001 QT mov is showing up as 23976/100:

```
Frame rate                               : 23.976
Frame rate                               : 23.976 (23976/1000) FPS
FrameRate_Num                            : 23976
FrameRate_Den                            : 1000
```

The moov atoms indicate that box the video and closed captions are 888888 samples at 24000/1001:

<img width="1191" alt="Screen Shot 2022-08-20 at 1 14 04 AM" src="https://user-images.githubusercontent.com/40502255/185730062-8a51eaea-535b-43a7-8d5f-3d9416cc8828.png">

I attempted to extract the moov in order to provide the full header metadata, but when I run MediaInfo on that, it's correct, although the details about the individual streams is missing - I suspect it may have something to do with misreporting after parsing the actual caption data.

https://user-images.githubusercontent.com/40502255/185730341-7a23371c-7c82-452c-82eb-43b461bf073e.mov

Please let me know if you want me to send the full file.

**Comment by JeromeMartinez** [comment]
Specific to CDP tracks in MOV due to a mix of several undetected bugs, all fixed now.

Note: fixee have a side effect, e.g. with CDP at 30000/1001 and MOV at 29970/1000 (@plondino one of the file your provided in the past is like that) result for the text track is now:
```
Frame rate                               : 29.970 (29970/1000) FPS
Original frame rate                      : 29.970 (30000/1001) FPS
```
And all other tracks are listed at 29970/1000 only because there is no frame rate information in raw stream (ProRes or PCM).

This is because we implement the CDP spec in an exact manner, with 30000/1001, but there is no way to indicate in CDP 29970/1000 so an encoder is IMO legitimate to use the index for 30000/1001 in that case. Wondering if it is relevant to show the stream frame rate not same as container frame rate in the case the stream format does not permit to do the difference between 29970/1000 and 30000/1001.
