### ISSUE TITLE
Audio sampling rate is type float in XSD

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfo#638]
The audio sampling rate is typed as float in the XSD:

`<xsd:element name="SamplingRate" minOccurs="0" maxOccurs="1" type="xsd:float"/>`

Is there a use case for fractional samples/second, or should this be of type integer? In the XML it appears to be an int:

`<SamplingRate>48000</SamplingRate>`

**Comment by JeromeMartinez** [comment]
If I remember well I faced once a 48000/1.001 stream...
In theory there is no technical limitation to a float sample rate so I am reluctant to constrain this element to integer. Limitation is more >0.

**Comment by plondino** [comment]
Although, I do wonder if you really wanted to capture the above that you'd want to use fractions to be precise, as the float value would be 47952.0479520479520...

**Comment by JeromeMartinez** [comment]
> Having a hard time visualizing how 48000/1.001 would work in practice

Well, one day someone decided to use 30/1.001 instead of 30 and now we handle float video frame rates... Same for audio, the second is an arbitrary slice of time and audio sampling rate may also be a float without changing the way samples are stored. imagine that someone wants to change 30 to 30/1.001 for video without resampling the audio and wanting to be precise, audio would be 48000/1.001.

In MOV, 29.97 video is stored with duration of 1001 and timescale of 30000, audio would be stored with duration of 1001 and timescale of 48000000.

> Although, I do wonder if you really wanted to capture the above that you'd want to use fractions to be precise, as the float value would be 47952.0479520479520...

We would do as for video (we show 29.970 instead of 29,97002997...), so 47952.048. But tested on a Matroska file and a MOV file with hand made changes, currently we don't support it (sampling rate is rounded with 0 decimal after comma), it could change in the future (I would be curious to know if I get such content in my sample files).
