### ISSUE TITLE
Mediainfo Dark Mode 

### ISSUE THREAD

**Issue by userzzzq** [MediaArea/MediaInfo#672]
support win10/win11 dark mode

**Comment by Thermalzombie** [comment]
Would like this to please.

**Comment by Thermalzombie** [comment]
Could you not at lease add an option for the text view to set black background white font.  Thanks?

**Comment by cjee21** [comment]
Looks like this is possible to implement. Just need to figure out how to detect current Windows mode and switch at runtime.

![Screenshot 2024-05-19 161718](https://github.com/MediaArea/MediaInfo/assets/77721854/17742d48-5276-4a38-9625-3ccf24de32de)
![Screenshot 2024-05-19 162138](https://github.com/MediaArea/MediaInfo/assets/77721854/8cd54d4f-c931-4d1d-9330-f13f1e74b4e6)

**Comment by cjee21** [comment]
I have implemented a very basic dark mode that can be toggled in the Options menu with the following limitations:
- It does not follow Windows current mode.
  - This requires checking the current Windows mode on application startup as well as detecting changes to Windows mode while the application is running which I am not able to implement.
- It does not remember the user preferred mode and will always default to light mode.
- The MediaInfo logo in the About window is not visible in dark mode because it is black.
- Some pages might still be displayed in light mode.

Do you want me to make a pull request for this?

![Screenshot 2024-05-19 175555](https://github.com/MediaArea/MediaInfo/assets/77721854/a9c9acb4-0be8-4351-9fc7-a72705ab509d)
