### ISSUE TITLE
Location of v23.06 Media Info XSD

### ISSUE THREAD

**Issue by joe-sciame-wm** [MediaArea/MediaInfo#742]
Hi Jerome,

Can you point me to the Media Info v23.06 XSD? I can see one here that was updated 8 months ago. https://github.com/MediaArea/MediaAreaXml/tree/master

**Comment by JeromeMartinez** [comment]
I forgot to merge https://github.com/MediaArea/MediaAreaXml/pull/62 :(.
Done.

**Comment by joe-sciame-wm** [comment]
Is this the file we are supposed to use from master? mpeg7-v2-extended.xsd. That is the file I see changed in that merge request. The one we had previously was mediainfo.xsd which came from https://github.com/MediaArea/MediaAreaXml/tree/master but its outdated.

**Comment by joe-sciame-wm** [comment]
Ok. so the one from 8 months ago is still good for 23.06?

**Comment by JeromeMartinez** [comment]
> Ok. so the one from 8 months ago is still good for 23.06?

As far as I know, there is no new "standard" field (the new ones are in the "extra" part, not limited).

**Comment by joe-sciame-wm** [comment]
Thanks Jerome! I pulled the xsd and so far so good.

**Comment by JeromeMartinez** [comment]
Argh, this element should not have been in the default XML output as it can be computed from other elements.
It is done, a MediaInfo release has it, so I added it to the XSD.
In the future this element may disappear from the the default XML output (it will be still available in MediaConch because it uses the "full" XML output which cointains computed values from other XML elements, no XSD there, used only for MediaConch internal stuff).

**Comment by joe-sciame-wm** [comment]
Thanks Jerome! Is there an XSD for the full output? or only the default output?

**Comment by JeromeMartinez** [comment]
XSD only for standard output.
