### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Dmole** [MediaArea/MediaInfo#84]
Please add build instructions to README.md and a link from https://mediaarea.net/en/MediaInfo/Support/Build_From_Sources to https://github.com/MediaArea/MediaInfo

maybe something like
`apt install build-essential libtool automake libzen-dev pkg-config;
cd Project/GNU/CLI;
./autogen.sh;
./configure;
make
`
only configure.ac is broken.

**Comment by JeromeMartinez** [comment]
> only configure.ac is broken.

What do you mean?

**Comment by Dmole** [comment]
Its not using libzen properly but without Build instructions maybe there really is an unmet dependency (it sometimes happen 2 different libraries have the same name). So please add Build instructions.

**Comment by JeromeMartinez** [comment]
Please be more explicit with "broken" or "not using properly". This is generic complain which does not permit us to understand the source of the issue you have. Which package do you use, which command do you try to run, which platform etc.
We'll add more detailed instructions, in the meanwhile you can use the [all in one package](https://mediaarea.net/download/binary/mediainfo/0.7.88/MediaInfo_CLI_0.7.88_GNU_FromSource.tar.gz) which has a build script and includes dependencies like libzen.

**Comment by JeromeMartinez** [comment]
@Dmole I saw your comment on Ubuntu tracker.

There are several issues in one ticket, and this is not possible to track things with this method.
So:
- OK, there are missing build instructions, this is the purpose of this ticket. in the meanwhile you can use the "all in one package" (download, unpack and run the script at the root) and does not prevent you to either compile yourself or test the Ubuntu package we provide on the [Ubuntu dedicated page](https://mediaarea.net/MediaInfo/Download/Ubuntu). Note that the Debian/Ubuntu package building rules are not complex (just requesting libzen-dev libz-dev..., cd /Project/GNU/Library && make).
- A file can not be read by MediaInfo. Test it without extra (no $F, you add complexity without reason) and report it in a separate ticket. Don't assume a problem (e.g. you say it is about Matroska but you did not test my command so impossible to know if it is due to Matroska with the binary on your machine)
- The error code are not good from your point of view. Open a ticket about that (and only that, nothing else, so no e.g. Matroska not read issue, stderr stuff...).
- You want and error message if the file is not accessible. Open a ticket about that (and only that, nothing else, so no e.g. Matroska not read issue, exit code stuff...).

More globally: be more precise. "broken" or "not using properly" does not help the developers.
"using git bisect" is another step, but first we need to agree about the exact issue else we'll reject the potential patch or the "origin" of the issue until we can reproduce issue.

You said: "As already stated the mediainfo change log leads me to believe otherwise; upstream might fix it." but you did not test the binaries we provides nor tested the "all in one" packages. We provide several solution, maybe not exactly the one you expect but there are solutions. And I am the upstream and believe that we did not touch to such kind of problem.

**Comment by g-maxime** [comment]
https://github.com/MediaArea/MediaInfo/commit/43a35290f835194dae8907e7cf25181d6c87b074
