### ISSUE TITLE
Select default view on Linux

### ISSUE THREAD

**Issue by influential-eliot** [MediaArea/MediaInfo#926]
Hi, I really like this program and use it a lot, but I don't know how to default the view to text view.

How is that done?

**Comment by JeromeMartinez** [comment]
which OS?

**Comment by influential-eliot** [comment]
Hiya, sorry, I forgot to include that ... it's Debian 12, wayland, gnome 43.9 ... I switched from Windows a little while ago ... it's quite nice that it isn't deciding everything for me!! 😅

**Comment by JeromeMartinez** [comment]
Currently the Linux GUI does not have much options, so not possible.
On our ToDo-list but not a priority (sponsored features have priority and we are already late on them).

**Comment by influential-eliot** [comment]
Ah, OK ... good luck with that, mate!

I'll find something else to get what I need. 👍 

Thanks anyway. 🙂 

---

**PS** - What equals a sponsored feature? Like, how much money does it cost to put something in that list?

**Comment by JeromeMartinez** [comment]
> PS - What equals a sponsored feature? Like, how much money does it cost to put something in that list?

We provide [professional services](https://mediaarea.net/Services), and we know that it is expensive for a private person.
We also started a [vote from donators](https://mediaarea.net/Vote) in order to let donators sharing the cost of a request, we could add this request to the list, but we are also late on it.
Note that it is open source and anyone may propose a patch, we would accept it (we are fine with features not developed by us, everyone can develop this feature for cheaper than us).

In practice, on our side we would like to refactor the GUIs on all platforms before implementing a preference window everywhere but we are very late (years) on that, so this request is actually included in a bigger one for when we have the time to have this refactored GUI.

**Comment by influential-eliot** [comment]
Ahh ... this is all brilliant information to have ... many thanks, @JeromeMartinez ... if I find the ability, I will try to contribute in whatever monetary fashion that I can.

Monetary because I really cannot code for toffee! 😅 

Cheers!

( _But I will try forking this to change some things ... then will give up when I don't understand how to make any of that actually do something 😅 😅 😅 😅 - that's not me being weird ... I'm just laughing at myself!!_ )
