### ISSUE TITLE
MediaInfo icon under Windows 11

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaInfo#972]
Received by email.

***

Hi,
when you select to show MediaInfo under the context menu, dann the entry "Mediainfo"
appears, but without icon.

The registry entry is wrong.
You insert "ICON" -> "E:\MediaInfo\MediaInfo.exe"

That is wrong. You have to specify the icon to use.
Under Windows 11 the entry should be:
ICON -> E:\MediaInfo\MediaInfo.exe,0

E ist the drive name (path) where Mediainfo is installed in my case E.
Also the entry do not need quotation marks.

Greetings

**Comment by cjee21** [comment]
@JeromeMartinez This is about the legacy context menu since we have not rolled out the Windows 11 one yet...

1. Windows 11 did not change anything regarding legacy shell extensions. It still appears in the legacy context menu (Show more options). If it works on previous Windows, it will still work on Windows 11.
2. It works properly on my Windows 11 system since Windows 11 was released until now. I cannot reproduce missing icon.
3. I am not sure if I am looking at the right place but this is what MediaInfo wrote to registry which seems correct:
    ![Screenshot 2024-11-24 233933](https://github.com/user-attachments/assets/96a0cae6-0719-4e6e-a5cd-e56c82248368)
4. The quotes are likely needed since default install location is Program Files which contains spaces.
5. There should be no need to specify which icon. The first icon in MediaInfo.exe will be used which is the correct MediaInfo icon. Same with modern context menu that we are working on.
6. The icon embedded in MediaInfo.exe has an ID of MAINICON and not an integer so I am not sure the suggestion even works.
    ![Screenshot 2024-11-24 235134](https://github.com/user-attachments/assets/def2a917-b7b6-452a-846f-fa129dc6c244)

Finally, I will not be making any changes to this since the legacy context menu is beyond my area and I do not even know where is the code that writes the icon to registry.

**Comment by JeromeMartinez** [comment]
Thank you.
This is what I thought, so I close for the moment as "can not reproduce".

**Comment by cjee21** [comment]
Took a look at how Microsoft's app do it:
![Screenshot 2024-11-25 000757](https://github.com/user-attachments/assets/cac08c6d-ecff-42e8-af7a-8d881d23dec7)

So no quotes needed and they are using resource ID to identify the icon.

But MediaInfo with quotes and using default icon has been working for years on various Windows versions so no need to change.
